import React, { useEffect, useState } from 'react';
import { GitCompare, Download } from 'lucide-react';
import type { ComparisonMatrixRow } from '../../types';
import { agentService } from '../../services/agentService';
import { ComparisonTable } from '../../components/research/ComparisonTable';
import { Button } from '../../components/common/Button';

export const Comparison: React.FC = () => {
  const [rows, setRows] = useState<ComparisonMatrixRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    agentService.getComparisonMatrix()
      .then(setRows)
      .catch(loadError => setError(loadError instanceof Error ? loadError.message : 'Could not load comparisons.'))
      .finally(() => setLoading(false));
  }, []);

  function exportCSV() {
    if (!rows.length) return;
    const values = [
      ['Paper', 'Year', 'Methodology', 'Dataset', 'Results', 'Limitations'],
      ...rows.map(row => [row.paperTitle, String(row.year), row.methodology, row.dataset, row.results, row.limitations]),
    ];
    const csv = values.map(row => row.map(value => `"${value.replaceAll('"', '""')}"`).join(',')).join('\r\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }));
    const link = document.createElement('a');
    link.href = url;
    link.download = 'research-comparison.csv';
    link.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-white flex items-center gap-2">
            <GitCompare className="w-6 h-6 text-blue-400" /> Cross-Paper Comparative Matrix
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Structured analysis generated by the Comparison Agent highlighting methodologies, datasets, empirical benchmarks, and trade-offs.
          </p>
        </div>

        <Button variant="secondary" size="sm" onClick={exportCSV} icon={<Download className="w-4 h-4" />}>
          Export Matrix
        </Button>
      </div>

      {error && <div role="alert" className="text-sm text-rose-300">{error}</div>}
      {loading ? <p className="text-sm text-slate-400">Loading comparison data...</p> : <ComparisonTable rows={rows} />}
    </div>
  );
};
