import React, { useEffect, useState } from 'react';
import { GitCompare, Download } from 'lucide-react';
import type { ComparisonMatrixRow } from '../../types';
import { agentService } from '../../services/agentService';
import { ComparisonTable } from '../../components/research/ComparisonTable';
import { Button } from '../../components/common/Button';

export const Comparison: React.FC = () => {
  const [rows, setRows] = useState<ComparisonMatrixRow[]>([]);

  useEffect(() => {
    agentService.getComparisonMatrix().then((data: ComparisonMatrixRow[]) => setRows(data));
  }, []);

  function exportCSV() {
    alert("Exporting Comparison Matrix to CSV / LaTeX format...");
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-white flex items-center gap-2">
            <GitCompare className="w-6 h-6 text-blue-400" /> Cross-Paper Comparative Matrix
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Structured analysis generated by the Comparison Agent highlighting methodologies, datasets, empirical benchmarks, and trade-offs.
          </p>
        </div>

        <Button variant="secondary" size="sm" onClick={exportCSV} icon={<Download className="w-4 h-4" />}>
          Export Matrix
        </Button>
      </div>

      <ComparisonTable rows={rows} />
    </div>
  );
};
