import React, { useState, useEffect } from 'react';
import { BookOpen, Search } from 'lucide-react';
import type { ResearchPaper } from '../../types';
import { agentService } from '../../services/agentService';
import { PaperCard } from '../../components/research/PaperCard';

export const Papers: React.FC = () => {
  const [papers, setPapers] = useState<ResearchPaper[]>([]);
  const [searchTerm, setSearchTerm] = useState('');

  useEffect(() => {
    agentService.getPapers().then((data: ResearchPaper[]) => setPapers(data));
  }, []);

  const filtered = papers.filter(p => 
    p.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
    p.summary.toLowerCase().includes(searchTerm.toLowerCase()) ||
    p.authors.some(a => a.toLowerCase().includes(searchTerm.toLowerCase()))
  );

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-white flex items-center gap-2">
            <BookOpen className="w-6 h-6 text-blue-400" /> Extracted Literature Intelligence
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Deep-extracted methodologies, dataset benchmarks, and structural claims generated by the Paper Intelligence Agent.
          </p>
        </div>

        <div className="relative w-full md:w-80">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
          <input 
            type="text" 
            placeholder="Search papers by keyword, dataset, author..." 
            value={searchTerm}
            onChange={e => setSearchTerm(e.target.value)}
            className="w-full bg-slate-900 border border-slate-800 rounded-xl pl-9 pr-3 py-2 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-blue-500"
          />
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {filtered.map(paper => (
          <PaperCard key={paper.id} paper={paper} />
        ))}
      </div>
    </div>
  );
};
